name: Build & Test Contact Form Project

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-test:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with Coverage
        run: |
          dotnet test --configuration Release --no-build --verbosity normal
          dotnet reportgenerator -reports:TestResults/*.trx -targetdir:coverage-report -reporttypes:Html
          echo "##vso[task.setvariable variable=coverageReportPath]$(System.DefaultWorkingDirectory)/coverage-report/index.html"
