name: CSharpier Format Check

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      format:
        description: "Run CSharpier format check"
        required: true
        default: true
        type: boolean

jobs:
  csharpier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Run CSharpier Check
        run: dotnet csharpier --check .

      - name: Run CSharpier Formatting
        if: ${{ github.event.inputs.format == 'true' }}
        run: dotnet csharpier .

      - name: Commit and Push Changes
        if: ${{ github.event.inputs.format == 'true' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply CSharpier formatting"
          if [ "${{ github.ref_name }}" == "main" ]; then
            git checkout -b csharpier-formatting
            git push origin csharpier-formatting
            gh pr create --title "Apply CSharpier formatting" --body "This PR applies CSharpier formatting to the codebase."
          else
            git push origin HEAD:${{ github.ref_name }}
          fi
